# <player> <killer> <time> <slots> <onlines> <bed> <purple-team> <yellow-team> <team> <item>
server-name: Rush1

messages:
  prefix: "§6[§eRush§6]"
  join-message: "§e<player> vient de rejoindre le §6Rush §e! <<onlines>/<slots>>"
  quit-message: "§e<player> a quitté la partie."
  countdown: "§eLe rush commence dans §6<time> §esecondes !"
  killed-by-player: "§6<player> §ea été tué par §6<killer> !"
  death: "§6<player> §ea cassé sa pipe !"
  eliminate: "§6<player> §ea été éliminé !"
  spectator-join: "§eLe jeu a déjà démarré !"
  starting: "§eLe jeu démarre !"
  bed-destroy: "§eLe lit §6<bed> §ea été détruit par §6<player> §e!"
  ally-bed-destroy: "§eVous ne pouvez pas détruire votre lit !"
  winning-broadcast: "§eBravo à l'équipe <team> §equi gagne le Rush !"
  winning-solo-broadcast: "§eBravo à <player> de l'équipe <team> qui remporte seul ce RUSH !"
  winners-message: "Vous avez gagné le RUSH !"
  no-winner: "Il semble n'y avoir aucun gagnant, tout le monde est mort !"
  slots-not-full: "Il n'y a pas assez de joueur pour commencer la partie !"
  killer-message: "§eTu viens de tuer §6<player> §e!"
  last-seconds: "Vous serez bientot au lobby..."
  no-pvp: "§cVous ne pouvez pas taper ce joueur maintenant !"
  no-break: "§cVous ne pouvez pas casser de block maintenant !"
  item-buy: "§eVous venez d'acheter : <item>"
  out-zone: "§cRevenez dans la zone de jeu !"

  global-chat: "§bGLOGAL: §f<team> §f| <player> §f: §7"
  team-chat: "§bTEAM: §f<player> §b: §f"
  spectator-chat: "§7SPECTATOR <player> : §7§i"

  force-stop: "§6Le rush a été arrêté de force: "
  no-game: "§4Erreur: §cAucune game de libre, retour au lobby."

bungeecord:
  lobby-server-name: "lobby"

  errors:
    buy: "§cUne erreur est survenue lors du retrait de vos <item>s, veulliez contacter un Staff !"

#Les lits ne sont pas à mettre dans la list, tous les autres blocks ne pourront être posés/cassés
place-break-list:
  - SANDSTONE
  - WOOD
  - TNT

shops:
    display-names:
      diamond: "§bDiamant"
      gold: "§eOr"
      iron: "§7Fer"
      bronze: "§6Bronze"
      price-prefix: "§e➡"